version: "3.3"
services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfile/Backend

  autotest:
    container_name: autotest
    depends_on: 
      - backend
    extra_hosts:
      testapp.local: 127.0.0.1
    build:
      context: .
      dockerfile: ./dockerfile/Autotest
