version: "3.3"
services:

  backend:
    network_mode: host
    build:
      context: ${BACKEND_DIR}
      dockerfile: Dockerfile

  autotest:
    container_name: autotest
    network_mode: host
    depends_on: 
      - backend
    extra_hosts:
      - "testapp.local:127.0.0.1"
    build:
      context: .
      dockerfile: Dockerfile
