version: 2.1

commands:
  run_tests:
    steps:
      - checkout

      - restore_cache:
          key: node--{{ checksum "package-lock.json" }}
      - run:
          name: "Building tests"
          command: "npm install && npx playwright install && npx playwright install deps"
      - save_cache:
          key: node--{{ checksum "package-lock.json" }}
          paths:
            - ~/tests/node_modules/
      - run:
          name: "Running tests"
          command: "npx playwright test"

jobs:
  preset_and_run_tests:
    machine:
      image: ubuntu-2004:202107-02
    working_directory: ~/tests
    steps:
      - run_tests


workflows:
  commit:
    jobs:
      - preset_and_run_tests