version: 2.1

commands:
  run_tests:
    working_directory: ~/tests
    steps:
      - checkout
      - run: "docker-compose up"


jobs:
  preset_and_run_tests:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run_tests


workflows:
  commit:
    jobs:
      - preset_and_run_tests