version: 2.1

commands:
  run_tests:
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - 70:99:d5:0c:5f:33:a2:1a:93:60:28:b1:67:9a:56:5a

      - run:
          name: "Pull backend repository"
          working_directory: ~/backend
          command: "git clone git@github.com:USATUKirill96/circleci-backend.git"
      
      - run:
          name: "Installing packages"
          command: "sudo apt update && apt-add repository ppa: deadsnakes/ppa &&apt install software-properties-common  python3.7 -y && python3.7 -m pip install -r requirements.txt"
          working_directory: ~/backend/circleci_backend

      - run:
          name: "Running django server"
          command: "python3.7 manage.py runserver 8051"
          working_directory: ~/backend/circleci_backend

      - restore_cache:
          key: node--{{ checksum "~/tests/package-lock.json" }}
      - run:
          name: "Building tests"
          command: "npm install && npx playwright install && npx playwright install-deps"
      - save_cache:
          key: node--{{ checksum "~/tests/package-lock.json" }}
          paths:
            - ~/tests/node_modules/
      - run:
          name: "Running tests"
          command: "npx playwright test"

jobs:
  preset_and_run_tests:
    machine:
      image: ubuntu-2004:202107-02
    working_directory: ~/tests
    steps:
      - run_tests


workflows:
  commit:
    jobs:
      - preset_and_run_tests