version: 2.1

commands:
  run_tests:
    steps:
      - checkout
      - run:
          name: "Building tests"
          command: "npm install && npx playwright install"
      - run:
          name: "Running tests"
          command: "npx playwright tests"

jobs:
  preset_and_run_tests:
    machine:
      image: ubuntu-2004:202107-02
    working_directory: ~/tests
    steps:
      - run_tests


workflows:
  commit:
    jobs:
      - preset_and_run_tests