# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test-run:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: "setting env"
          command: "npm install && npx playwright install && npx playwright install-deps"
      - run:
          name: "running tests"
          command: "npx playwright test"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:

  commit:
    jobs:
      - test-run

  scheduler:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - test-run
